ignore:
  - slashtag_server/.venv
  - .vscode/*

refactor:
  skip: []

metrics:
  quality_threshold: 25.0

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}
